blank_issues_enabled: true
contact_links:
  - name: "Cómo contribuir (CONTRIBUTING.md)"
    url: https://github.com/
    about: "La forma más rápida de añadir un proyecto es un Pull Request con un archivo YAML."
